language: python
python:
- '3.5'
- '3.6'
script:
- touch /tmp/foo
deploy:
  provider: pypi
  user: bbrancottest
  password:
    secure: MmMWDmA/Gx9Yt9iufMcGtnMAWhm48jvJ00x8WPw5B7wfjkEkSSbOy/KXuyGxCPIW+mSaIdKEIlktZF1YZ1fQKyxq1cu9kpHnQlUtlBPstz3pIR3eKOlYtSdxIuoZFdVzpOkwFqFm4x0HDAqrzLLmlOlL+79Z9yIQQBun/mh4pcGcTkN3cmryvB2lHsKAF8AmIsMUjg0t50zAGFHw1uEZHyGy3q5Hn3ElgDKYWemSeRkPvMn45Qfy35uA2o2hQ7bp01fDuVSm21hxhWaUKB7bX4OE7G05muaa62zS5lRu8aUQw5q6r598OE/64u+ZpLUjgA2UKvJGgfD9TiaVEgWEE8JFgtuEqpbdD5OZDLcdr79FfUMhUkEqgibipYvrakXMqrT/0F0f3+ijjUfzlivpp/dkvNX91tn5el5Nh0NnsJ9CDYhe97BMzXBDF921YdRfF6xLMHqULiZgZ118YFmzwn5WXRoJ1TzMLdKEy71BiqojEaIwSvlt1S+EgA5rjAyxMHhkcX6qrTJnb/yytbPefar7mLe38omICGB90k/O/15yzJxqjDBL1vjacrO3zvbPSlNEEWRO54VNTFNT3VMdp+4uvXsS8GirhH9llAr8/Evq9SmEdEXLctA4RZM05LAqi74TjM6Slvvw0Fbrea0/ol7YUA4UkYRPA5lACRTNh5M=
  server: https://test.pypi.org/legacy/
  on:
    tags: true
    python: 3.6
    branch: master
