language: python
python:
- '3.6'
script:
- touch /tmp/foo
deploy:
  provider: pypi
  user: bbrancot
  #user: bbrancottest
  #server: https://test.pypi.org/legacy/
  password:
    #secure: MmMWDmA/Gx9Yt9iufMcGtnMAWhm48jvJ00x8WPw5B7wfjkEkSSbOy/KXuyGxCPIW+mSaIdKEIlktZF1YZ1fQKyxq1cu9kpHnQlUtlBPstz3pIR3eKOlYtSdxIuoZFdVzpOkwFqFm4x0HDAqrzLLmlOlL+79Z9yIQQBun/mh4pcGcTkN3cmryvB2lHsKAF8AmIsMUjg0t50zAGFHw1uEZHyGy3q5Hn3ElgDKYWemSeRkPvMn45Qfy35uA2o2hQ7bp01fDuVSm21hxhWaUKB7bX4OE7G05muaa62zS5lRu8aUQw5q6r598OE/64u+ZpLUjgA2UKvJGgfD9TiaVEgWEE8JFgtuEqpbdD5OZDLcdr79FfUMhUkEqgibipYvrakXMqrT/0F0f3+ijjUfzlivpp/dkvNX91tn5el5Nh0NnsJ9CDYhe97BMzXBDF921YdRfF6xLMHqULiZgZ118YFmzwn5WXRoJ1TzMLdKEy71BiqojEaIwSvlt1S+EgA5rjAyxMHhkcX6qrTJnb/yytbPefar7mLe38omICGB90k/O/15yzJxqjDBL1vjacrO3zvbPSlNEEWRO54VNTFNT3VMdp+4uvXsS8GirhH9llAr8/Evq9SmEdEXLctA4RZM05LAqi74TjM6Slvvw0Fbrea0/ol7YUA4UkYRPA5lACRTNh5M=
    secure: n7x0WJ6tHvu3TMV8CRyWgf0rFiYsFN1+xSiXqEnm7pO/erJZ/InRm7R/6AyaK5pvEqvNgSd/FFF/TigoG3aF/4hDhwrzcmuZ7OIemqj9VM6xVIaj6nDO1E8siWpq9ElPJBo4Ura/D9xJ+byIdW/rhFtGcfuZ2Ggp5ygbdynQoEQLkLDNamjiBW3dGXldod/Hwikj9/prpXbhvFSrBsRZNmB/0jM5l6i38nBKK1xivYJx8riEaIKYssOW3Q69kx6sdLvMRh8ljWo2GOd+5lKdGIfqYkM2VSmsrUFT614wc0hJrOB6t89zVUhhsVLj08RdcQuMMDHx7k5pXKUmGMbZbLizm1EQlX486Nmcm972FfG+AHLNZ1WCngDYFSR8UL6qXo+OJfEHUStMXWfTm1eALtsok4RfZCzbdYmVYQi9HFNAipaRh5YPyc0od4K3JkWul/z/iwexXbV6dg++j521OmNnIYUYSiThsRTKjVbwDJUCRTwRr+Om6XVSp6L5ZXUloHwvtOJA+oXa0Qpu63hPanCgeJdSiPnIHrlu5FrmuPbju0W30bXQzCnNDPbT6pIW04KOMYN5HKC55UHOe7PTioJb6nIwJR/fKDHy1m03zGrehxwPaGVDb9g32Vdvp6ThjZdlSSfFdRsWQqnflgvgQX2DJ2myexHWUGhMRcOyNiU=
  distributions: "sdist bdist_wheel" # Your distributions here
  on:
    tags: true
    python: 3.6
    branch: master
